//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Counter_Control
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnergyMetersEntities : DbContext
    {
        public EnergyMetersEntities()
            : base("name=EnergyMetersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int DeleteMeterAndReadouts(Nullable<int> mETER_ID)
        {
            var mETER_IDParameter = mETER_ID.HasValue ?
                new ObjectParameter("METER_ID", mETER_ID) :
                new ObjectParameter("METER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMeterAndReadouts", mETER_IDParameter);
        }
    }
}
